#!/bin/sh

if [ -f "$HOME/.nvm/nvm.sh" ]; then
  . "$HOME/.nvm/nvm.sh"
fi

if [ -d "$HOME/snap/code/241/.local/share/pnpm/bin" ]; then
  export PNPM_HOME="$HOME/snap/code/241/.local/share/pnpm/bin"
  export PATH="$PNPM_HOME:$PATH"
fi

pnpm lint-staged
pnpm lint
pnpm typecheck
